// <auto-generated />
using System;
using AdessoWorldLeague.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdessoWorldLeague.Infrastructure.Migrations
{
    [DbContext(typeof(AdessoWorldLeagueDbContext))]
    partial class AdessoWorldLeagueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdessoWorldLeague.Domain.Models.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02fd27d4-3d1e-42e3-b68d-7523909edd6a"),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("f655f39f-c844-4973-bb7a-e675641f6981"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("d516f99d-2f8a-4ecf-bec8-79a407744bf0"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("ae1ba129-93d7-4bb3-916d-ddc0db6e0b67"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("533060a2-f88f-46ed-95a7-49b99441f6b5"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("0794140c-e524-404a-b3f2-528c3e679a96"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("63a54ea0-4da1-429f-87b9-31ff6adaf662"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("156d9e12-9dbd-4990-a57e-c7f145b8e0eb"),
                            Name = "Belgium"
                        });
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Models.DrawResults.DrawResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DrawRecords");
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Models.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("81c6667b-7a8f-4a22-a634-1d3ed0f6bf94"),
                            CountryId = new Guid("02fd27d4-3d1e-42e3-b68d-7523909edd6a"),
                            Name = "Adesso Istanbul"
                        },
                        new
                        {
                            Id = new Guid("c7534f74-6ebb-4ba9-9e0b-79816fce7f61"),
                            CountryId = new Guid("02fd27d4-3d1e-42e3-b68d-7523909edd6a"),
                            Name = "Adesso Ankara"
                        },
                        new
                        {
                            Id = new Guid("62f8551e-ac4a-4908-be70-3afc7824541c"),
                            CountryId = new Guid("02fd27d4-3d1e-42e3-b68d-7523909edd6a"),
                            Name = "Adesso Antalya"
                        },
                        new
                        {
                            Id = new Guid("dfd29cb7-1665-47e4-bdb6-ee6e6747b360"),
                            CountryId = new Guid("02fd27d4-3d1e-42e3-b68d-7523909edd6a"),
                            Name = "Adesso İzmir"
                        },
                        new
                        {
                            Id = new Guid("362b0fce-709e-4a1c-9f45-e4a52c39a15b"),
                            CountryId = new Guid("f655f39f-c844-4973-bb7a-e675641f6981"),
                            Name = "Adesso Berlin"
                        },
                        new
                        {
                            Id = new Guid("d6c8cad7-a06a-46d7-83ad-bbd125e633f7"),
                            CountryId = new Guid("f655f39f-c844-4973-bb7a-e675641f6981"),
                            Name = "Adesso Frankfurth"
                        },
                        new
                        {
                            Id = new Guid("915e8c30-8997-4f93-b87b-76fa6a051b63"),
                            CountryId = new Guid("f655f39f-c844-4973-bb7a-e675641f6981"),
                            Name = "Adesso Munich"
                        },
                        new
                        {
                            Id = new Guid("6fd8ef6a-4fb2-4b45-a7fd-b603ef57880e"),
                            CountryId = new Guid("f655f39f-c844-4973-bb7a-e675641f6981"),
                            Name = "Adesso Dortmund"
                        },
                        new
                        {
                            Id = new Guid("c8681e78-17a9-4150-bac7-4a21f0377ecb"),
                            CountryId = new Guid("d516f99d-2f8a-4ecf-bec8-79a407744bf0"),
                            Name = "Adesso Paris"
                        },
                        new
                        {
                            Id = new Guid("e41998d9-a41c-48bc-90b4-0204a10628a9"),
                            CountryId = new Guid("d516f99d-2f8a-4ecf-bec8-79a407744bf0"),
                            Name = "Adesso Lyon"
                        },
                        new
                        {
                            Id = new Guid("87507cba-8764-4cec-836e-ab662d8a00e4"),
                            CountryId = new Guid("d516f99d-2f8a-4ecf-bec8-79a407744bf0"),
                            Name = "Adesso Marseille"
                        },
                        new
                        {
                            Id = new Guid("ed652bdb-bb5b-430e-9ba7-927d268c1f85"),
                            CountryId = new Guid("d516f99d-2f8a-4ecf-bec8-79a407744bf0"),
                            Name = "Adesso Nice"
                        },
                        new
                        {
                            Id = new Guid("3b202592-399e-4dfa-8916-f56d50c72a12"),
                            CountryId = new Guid("ae1ba129-93d7-4bb3-916d-ddc0db6e0b67"),
                            Name = "Adesso Amsterdam"
                        },
                        new
                        {
                            Id = new Guid("d9bd68f9-b08f-4e23-accf-91486e7804f6"),
                            CountryId = new Guid("ae1ba129-93d7-4bb3-916d-ddc0db6e0b67"),
                            Name = "Adesso Rotterdam"
                        },
                        new
                        {
                            Id = new Guid("97fc80ad-49ea-4074-8814-79157def68fb"),
                            CountryId = new Guid("ae1ba129-93d7-4bb3-916d-ddc0db6e0b67"),
                            Name = "Adesso Lahey"
                        },
                        new
                        {
                            Id = new Guid("a280a7bb-bb04-4ab3-bf88-6a26129a16bd"),
                            CountryId = new Guid("ae1ba129-93d7-4bb3-916d-ddc0db6e0b67"),
                            Name = "Adesso Eindhoven"
                        },
                        new
                        {
                            Id = new Guid("5c59b52f-033d-46db-82be-0e994a54111b"),
                            CountryId = new Guid("533060a2-f88f-46ed-95a7-49b99441f6b5"),
                            Name = "Adesso Lisbon"
                        },
                        new
                        {
                            Id = new Guid("2602d1bf-f26b-41e6-b2c9-838de6d058c6"),
                            CountryId = new Guid("533060a2-f88f-46ed-95a7-49b99441f6b5"),
                            Name = "Adesso Porto"
                        },
                        new
                        {
                            Id = new Guid("6e461e04-5827-47c5-96f8-ddad6db8b1f0"),
                            CountryId = new Guid("533060a2-f88f-46ed-95a7-49b99441f6b5"),
                            Name = "Adesso Braga"
                        },
                        new
                        {
                            Id = new Guid("1f5500c4-5ff3-4269-96fb-1874debcb55c"),
                            CountryId = new Guid("533060a2-f88f-46ed-95a7-49b99441f6b5"),
                            Name = "Adesso Coimbra"
                        },
                        new
                        {
                            Id = new Guid("64fb783e-bdcc-4aca-b897-02ad68bd1dde"),
                            CountryId = new Guid("0794140c-e524-404a-b3f2-528c3e679a96"),
                            Name = "Adesso Rome"
                        },
                        new
                        {
                            Id = new Guid("d0455711-cf9e-4701-9d91-01d6e83c5af1"),
                            CountryId = new Guid("0794140c-e524-404a-b3f2-528c3e679a96"),
                            Name = "Adesso Milano"
                        },
                        new
                        {
                            Id = new Guid("df160af5-2dd4-43e1-973e-94220d6b26af"),
                            CountryId = new Guid("0794140c-e524-404a-b3f2-528c3e679a96"),
                            Name = "Adesso Venice"
                        },
                        new
                        {
                            Id = new Guid("3ab10003-9b18-4124-8d9e-897cdfc9e9b8"),
                            CountryId = new Guid("0794140c-e524-404a-b3f2-528c3e679a96"),
                            Name = "Adesso Napoli"
                        },
                        new
                        {
                            Id = new Guid("b52498f3-29eb-414f-b31c-c8991a1bc88a"),
                            CountryId = new Guid("63a54ea0-4da1-429f-87b9-31ff6adaf662"),
                            Name = "Adesso Madrid"
                        },
                        new
                        {
                            Id = new Guid("4d70e9a1-dfb5-4b68-a9d9-0c58b59df50f"),
                            CountryId = new Guid("63a54ea0-4da1-429f-87b9-31ff6adaf662"),
                            Name = "Adesso Barcelona"
                        },
                        new
                        {
                            Id = new Guid("d65ea1d7-8718-490d-93da-bae1c642df2e"),
                            CountryId = new Guid("63a54ea0-4da1-429f-87b9-31ff6adaf662"),
                            Name = "Adesso Granada"
                        },
                        new
                        {
                            Id = new Guid("8314826f-cc9f-4681-bf43-32fca8a9531b"),
                            CountryId = new Guid("63a54ea0-4da1-429f-87b9-31ff6adaf662"),
                            Name = "Adesso Sevilla"
                        },
                        new
                        {
                            Id = new Guid("8fd80894-d022-4c6b-9c7d-c53a3909b77f"),
                            CountryId = new Guid("156d9e12-9dbd-4990-a57e-c7f145b8e0eb"),
                            Name = "Adesso Brussels"
                        },
                        new
                        {
                            Id = new Guid("404af8b7-b2c8-45a6-8d9d-1c71ac819de2"),
                            CountryId = new Guid("156d9e12-9dbd-4990-a57e-c7f145b8e0eb"),
                            Name = "Adesso Anvers"
                        },
                        new
                        {
                            Id = new Guid("b01f492b-73ac-4c7e-9941-54ac8bfb5b5d"),
                            CountryId = new Guid("156d9e12-9dbd-4990-a57e-c7f145b8e0eb"),
                            Name = "Adesso Ghent"
                        },
                        new
                        {
                            Id = new Guid("de21d655-3265-4582-8e46-d358c5032534"),
                            CountryId = new Guid("156d9e12-9dbd-4990-a57e-c7f145b8e0eb"),
                            Name = "Adesso Brugge"
                        });
                });

            modelBuilder.Entity("DrawResultGroup", b =>
                {
                    b.Property<Guid>("DrawResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DrawResultId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("DrawResultGroup");
                });

            modelBuilder.Entity("GroupTeam", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("GroupTeam");
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Models.DrawResults.DrawResult", b =>
                {
                    b.OwnsOne("AdessoWorldLeague.Domain.Models.DrawResults.Ruler", "Ruler", b1 =>
                        {
                            b1.Property<Guid>("DrawResultId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DrawResultId");

                            b1.ToTable("DrawRecords");

                            b1.WithOwner()
                                .HasForeignKey("DrawResultId");
                        });

                    b.Navigation("Ruler")
                        .IsRequired();
                });

            modelBuilder.Entity("AdessoWorldLeague.Domain.Models.Teams.Team", b =>
                {
                    b.HasOne("AdessoWorldLeague.Domain.Models.Countries.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DrawResultGroup", b =>
                {
                    b.HasOne("AdessoWorldLeague.Domain.Models.DrawResults.DrawResult", null)
                        .WithMany()
                        .HasForeignKey("DrawResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdessoWorldLeague.Domain.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupTeam", b =>
                {
                    b.HasOne("AdessoWorldLeague.Domain.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdessoWorldLeague.Domain.Models.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
